
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 27 20:37:09 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 25;
  public static final int CONST = 43;
  public static final int CHAR = 16;
  public static final int LOWER = 41;
  public static final int GREATER = 39;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 33;
  public static final int LOWEREQUAL = 42;
  public static final int FOR = 31;
  public static final int MINUS = 23;
  public static final int RPAREN = 7;
  public static final int AND = 35;
  public static final int OR = 34;
  public static final int BOOL = 17;
  public static final int COMMA = 8;
  public static final int INC = 20;
  public static final int DIV = 29;
  public static final int PLUS = 11;
  public static final int IF = 18;
  public static final int DOT = 27;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int RBRACKET = 26;
  public static final int EQUAL = 12;
  public static final int ISEQUAL = 37;
  public static final int NEW = 24;
  public static final int error = 1;
  public static final int MUL = 28;
  public static final int PERCENT = 30;
  public static final int NUMBER = 14;
  public static final int BREAK = 32;
  public static final int IDENT = 15;
  public static final int VOID = 13;
  public static final int GREATEREQUAL = 40;
  public static final int ISNOTEQUAL = 38;
  public static final int LBRACE = 3;
  public static final int ELSE = 19;
  public static final int ENUM = 36;
  public static final int READ = 22;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int DEC = 21;
  public static final int PRINT = 9;
}

